apiVersion: apps/v1
kind: Deployment
metadata:
  name: results-service-deployment
  labels:
    app: results-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: results-service
  template:
    metadata:
      labels:
        app: results-service
    spec:
      containers:
        - name: results-service-container
          image: DOCKER_IMAGE_PLACEHOLDER:TAG_PLACEHOLDER
          ports:
            - containerPort: 8080
