name: CI/CD Multi-Module with Paketo to Azure AKS

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ACR_NAME: ${{ secrets.ACR_NAME }}
      RESOURCE_GROUP: ${{ secrets.AKS_RESOURCE_GROUP }}
      AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
      SERVICES: "user-service results-service move-service match-making-service"
      K8S_DEPLOYMENT_PATH: "k8s"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name $ACR_NAME

      - name: Set Environment Variables
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "ENV=prod" >> $GITHUB_ENV
            echo "TAG=prod-${GITHUB_SHA::7}" >> $GITHUB_ENV
          else
            echo "ENV=staging" >> $GITHUB_ENV
            echo "TAG=staging-${GITHUB_SHA::7}" >> $GITHUB_ENV
          fi

      - name: Build & Push Images using Paketo (with Spring Boot Gradle Plugin)
        run: |
          for SERVICE in $SERVICES; do
            IMAGE="$ACR_NAME.azurecr.io/$SERVICE:$TAG"
            ./gradlew :$SERVICE:bootBuildImage \
              -Dspring-boot.build-image.imageName=$IMAGE \
              -Dspring-boot.build-image.pullPolicy=IF_NOT_PRESENT
            docker push $IMAGE
          done

      - name: Get AKS Credentials & Create Namespace
        run: |
          # Get cluster credentials
          az aks get-credentials \
            --resource-group $RESOURCE_GROUP \
            --name $AKS_CLUSTER_NAME

          # Ensure namespace exists
          kubectl get namespace $ENV >/dev/null 2>&1 || kubectl create namespace $ENV

      - name: Create or Update Deployments
        run: |
          for SERVICE in $SERVICES; do
            # Replace placeholder image and tag with dynamic values
            # Assumes your YAML files are named like 'user-service-deployment.yaml'
            sed "s|DOCKER_IMAGE_PLACEHOLDER|$ACR_NAME.azurecr.io/$SERVICE|g; s|TAG_PLACEHOLDER|$TAG|g" \
              $K8S_DEPLOYMENT_PATH/$SERVICE-deployment.yaml > temp-deployment.yaml

            # Apply the updated YAML file to the cluster
            kubectl apply -f temp-deployment.yaml -n $ENV

            # Clean up the temporary file
            rm temp-deployment.yaml
          done

      - name: Verify Deployment Rollout
        run: |
          for SERVICE in $SERVICES; do
            kubectl rollout status deployment/$SERVICE-deployment -n $ENV
          done
