name: CI/CD Multi-Module with Paketo to Azure (Chess)

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ACR_NAME: ${{ secrets.ACR_NAME }}
      RESOURCE_GROUP: ${{ secrets.AKS_RESOURCE_GROUP }}
      AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name $ACR_NAME

      - name: Set Environment Variables
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "ENV=prod" >> $GITHUB_ENV
            echo "TAG=prod-${GITHUB_SHA::7}" >> $GITHUB_ENV
          else
            echo "ENV=staging" >> $GITHUB_ENV
            echo "TAG=staging-${GITHUB_SHA::7}" >> $GITHUB_ENV
          fi

      - name: Create Namespaces if not exist
        run: |
          kubectl create namespace prod || true
          kubectl create namespace staging || true

      - name: Build & Push Images (Paketo)
        run: |
          ./gradlew :user-service:bootBuildImage \
            --imageName=$ACR_NAME.azurecr.io/user-service:$TAG \
            --publishImage
          ./gradlew :results-service:bootBuildImage \
            --imageName=$ACR_NAME.azurecr.io/results-service:$TAG \
            --publishImage
          ./gradlew :move-service:bootBuildImage \
            --imageName=$ACR_NAME.azurecr.io/move-service:$TAG \
            --publishImage
          ./gradlew :match-making-service:bootBuildImage \
            --imageName=$ACR_NAME.azurecr.io/match-making-service:$TAG \
            --publishImage

      - name: Get AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group $RESOURCE_GROUP \
            --name $AKS_CLUSTER_NAME

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/user-service user-service=$ACR_NAME.azurecr.io/user-service:$TAG -n $ENV
          kubectl set image deployment/results-service results-service=$ACR_NAME.azurecr.io/results-service:$TAG -n $ENV
          kubectl set image deployment/move-service move-service=$ACR_NAME.azurecr.io/move-service:$TAG -n $ENV
          kubectl set image deployment/match-making-service match-making-service=$ACR_NAME.azurecr.io/match-making-service:$TAG -n $ENV

      - name: Verify Deployment Rollout
        run: |
          kubectl rollout status deployment/user-service -n $ENV
          kubectl rollout status deployment/results-service -n $ENV
          kubectl rollout status deployment/move-service -n $ENV
          kubectl rollout status deployment/match-making-service -n $ENV
