name: CI/CD Multi-Module with Paketo to Azure (Chess)

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ACR_NAME: ${{ secrets.ACR_NAME }}
      RESOURCE_GROUP: ${{ secrets.AKS_RESOURCE_GROUP }}
      AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name $ACR_NAME

      - name: Set Environment Variables
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "ENV=prod" >> $GITHUB_ENV
            echo "TAG=prod-${GITHUB_SHA::7}" >> $GITHUB_ENV
          else
            echo "ENV=staging" >> $GITHUB_ENV
            echo "TAG=staging-${GITHUB_SHA::7}" >> $GITHUB_ENV
          fi

      - name: Get AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group $RESOURCE_GROUP \
            --name $AKS_CLUSTER_NAME

      - name: Create Namespace if not exist
        run: |
          kubectl get namespace $ENV || kubectl create namespace $ENV

      - name: Docker Login to ACR
        run: echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_NAME }}.azurecr.io -u ${{ secrets.ACR_NAME }} --password-stdin


      - name: Build & Push Images (Paketo)
        run: |
          for SERVICE in user-service results-service move-service match-making-service; do
            IMAGE=${{ secrets.ACR_NAME }}.azurecr.io/$SERVICE:$TAG
            ./gradlew :$SERVICE:bootBuildImage -Dspring-boot.build-image.imageName=$IMAGE
            docker push $IMAGE
          done

      - name: Deploy to AKS
        run: |
          for SERVICE in user-service results-service move-service match-making-service; do
            kubectl set image deployment/$SERVICE $SERVICE=${{ secrets.ACR_NAME }}.azurecr.io/$SERVICE:$TAG -n $ENV
          done

      - name: Verify Deployment Rollout
        run: |
          kubectl rollout status k8s/user-service -n $ENV
          kubectl rollout status k8s/results-service -n $ENV
          kubectl rollout status k8s/move-service -n $ENV
          kubectl rollout status k8s/match-making-service -n $ENV
